name: Weekly Activity Report

on:
  workflow_dispatch: # Pozwala odpalić ręcznie

permissions:
  contents: read
  issues: write

jobs:
  report:
    runs-on: ubuntu-latest
    steps:
      - uses: wow-actions/activity-report@v1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          days: 60 # Zwiększamy zakres do 45 dni, żeby złapał Twoje commity sprzed miesiąca
